spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.85.166)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.85.167)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=epaydb))))
  redis:
    cluster:
      nodes: 10.1.85.160:7000,10.1.85.160:7001,10.1.85.160:7002,10.1.85.160:7003,10.1.85.160:7004,10.1.85.160:7005
frontend-host: http://lyu.dp.com:3000
