spring:
  application:
    name: dove-fetch
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: epaysch
    password: epaysch
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      configure-action: none
  redis:
    password: Acca@1234
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 2000
        min-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080